on:
  push:
  workflow_dispatch:

jobs:
  helloworld:
    runs-on: ubuntu-latest
    steps:
      
      - name: Get a clone of the current repo
        uses: actions/checkout@v4 

      - name: List all the files
        run:  ls  
        
      - name: Run the test
        run: ./gradlew test

     
